### ISSUE TITLE
parseOnSave not working

### ISSUE THREAD

**Issue by andy9a9** [yoctoproject/vscode-bitbake#107]
Every recipe's save execute the Bitbake parsing process even if the `parseOnSave` is set o `false`. I wanted to execute parsing only on request.
```json
"bitbake.pathToBuildFolder": "${workspaceFolder}/build",
"bitbake.pathToEnvScript": "${workspaceFolder}/components/yocto/layers/poky/oe-init-build-env",
"bitbake.pathToBitbakeFolder": "${workspaceFolder}/components/yocto/layers/poky/bitbake",
"bitbake.parseOnSave": false,
"python.autoComplete.extraPaths": [
    "${workspaceFolder}/components/yocto/layers/poky/bitbake/lib",
    "${workspaceFolder}/components/yocto/layers/poky/meta/lib"
],
"[python]": {
    "diffEditor.ignoreTrimWhitespace": false,
    "gitlens.codeLens.symbolScopes": [
        "!Module"
    ],
    "files.trimTrailingWhitespace": false
},
"[shellscript]": {
    "files.eol": "\n",
    "files.trimTrailingWhitespace": false
},
"task.saveBeforeRun": "always",
```

**Comment by deribaucourt** [comment]
Hello and thanks for the bug report!

This is an identified regression in the current release. It's been fixed in https://github.com/yoctoproject/vscode-bitbake/commit/a0c2434ec3b9a55ab651224e10c5bb74f6630cba

We plan a new release by the end of February. If this issue is too annoying for you and you want the fix right no, I suggest grabbing a nightly CI .vsix build from https://github.com/yoctoproject/vscode-bitbake/actions?query=branch%3Astaging 
This version is under development so you may have other issues. But we'd be glad to fix them if you encounter any :)
