### ISSUE TITLE
"bitbake.pathToBuildFolder" setting is automatically converted to absolute path

### ISSUE THREAD

**Issue by tq-steina** [yoctoproject/vscode-bitbake#109]
While configuring a custom env script using `bitbake.pathToEnvScript` I noticed that `bitbake.pathToBuildFolder` is implicitely converted to an absolute path, even if it is configured relatively. See my config:
```
    "bitbake.pathToEnvScript": "${workspaceFolder}/setup-environment",
    "bitbake.pathToBuildFolder": "build_tqma8",
```
For a deeper introspection I worked around using
```
    "bitbake.commandWrapper": "echo ",
```
and ended up with logging lines like
```
. /mnt/ci-meta-tq-kirkstone/setup-environment /mnt//ci-meta-tq-kirkstone/build_tqma8 && which devtool
 *  Executing script: echo  '. /mnt/ci-meta-tq-kirkstone/setup-environment /mnt/ci-meta-tq-kirkstone/build_tqma8 && which devtool'
 *  Bitbake process exited successfully
 *  Terminal will be reused by BitBake, press any key to close it.
```
Our custom script `setup-environment` can't cope with absolute paths, so this setup breaks.

**Comment by deribaucourt** [comment]
We do resolve all paths to absolute indeed. It's mostly useful to convert to/from docker containers which use different mount points (like kas-container).
Now that we have workingDir and shellEnv setting, I don't think absolute paths are needed to start bitbake.
So we could consider moving the absolute path resolution to just the parts where it is needed.
It makes sense for your use case and in general to respect relative paths.

However, I plan to keep `${workspaceFolder}` expanded to absolute because that's how VSCode forwards it to us. You'd rather have to use `./` in your settings.

Sounds good? I'll give it a shot, see if nothing breaks.

**Comment by tq-steina** [comment]
> We do resolve all paths to absolute indeed. It's mostly useful to convert to/from docker containers which use different mount points (like kas-container). Now that we have workingDir and shellEnv setting, I don't think absolute paths are needed to start bitbake. So we could consider moving the absolute path resolution to just the parts where it is needed. It makes sense for your use case and in general to respect relative paths.
> 
> However, I plan to keep `${workspaceFolder}` expanded to absolute because that's how VSCode forwards it to us. You'd rather have to use `./` in your settings.

I don't mind having `${workspaceFolder}`  expanded, I would expect that to expand. But please be aware I do not use `${workspaceFolder}` in `bitbake.pathToBuildFolder`, so I would not expect it to be expanded to an absolute path. 

Also I don't think VSCode forwards that config setting as an absolute path, rather you expanded it explicitely yourself. See https://github.com/yoctoproject/vscode-bitbake/blob/staging/client/src/lib/src/BitbakeSettings.ts#L36 and later https://github.com/yoctoproject/vscode-bitbake/blob/staging/client/src/lib/src/BitbakeSettings.ts#L51

> Sounds good? I'll give it a shot, see if nothing breaks.

So having to use `./` seems like a workaround to me. If one needs absolute paths, a proper base like `${workspaceFolder}` should be used, as shown in the default anyway.
