### ISSUE TITLE
Prevent the plugin from constantly changing my `.vscode/settings.json`

### ISSUE THREAD

**Issue by skycaptain** [yoctoproject/vscode-bitbake#194]
In my project, I use a `.vscode/settings.json` file. As I'm developing on a Mac and building in a Docker container, I appreciate the syntax highlighting that this extension provides. However, I would like to disable some of its additional features, such as editing the `.vscode/settings.json` file.

Since I build within a container, most of the added settings are either invalid (for example, paths in `python.analysis.extraPaths`) or conflict with my specific python formatting requirements. Currently, these issues compel me to either revert the changes before every commit or disable the extension altogether.

I've attempted to enable `bitbake.disableEmbeddedLanguagesFiles` and disable `bitbake.parseOnSave`, but unfortunately, these actions haven't resulted in the desired outcome.

**Comment by deribaucourt** [comment]
A lot of extensions like us need to configure other extensions or vscode settings. This is a VSCode limitation that is requested a lot since 2017 but hasn't been fixed. https://github.com/microsoft/vscode/issues/40233

We could implement a additional setting to disable any setting modification on our part though. Some of our features might be expected to now work if the settings are not how we want them though. So this should be properly explained in the documentation of the option.

**Comment by skycaptain** [comment]
Having the option to disable any setting modifications would be great and would resolve this issue. Most other extensions I use typically refer to their documentation for guidance on how to optimally configure project settings for VSCode.
