### ISSUE TITLE
Syntax highlighter doesn't handle triple-quotes in classes

### ISSUE THREAD

**Issue by rossburton** [yoctoproject/vscode-bitbake#3]
The highlighter is failing with triple quoted strings inside python blocks in .bbclass files.

For example, the first anon python block in `kernel.bbclass`.

![Screenshot 2023-11-27 at 11 34 42](https://github.com/yoctoproject/vscode-bitbake/assets/32394/42689cc4-85a2-4f8b-b0a6-b078169c9dc1)

A minimal reproducer:

```
python __anonymous () {
    s = """
    nested " quotes shouldnt change the highlighting
    """
    s = "foo".upper()
}
```

![Screenshot 2023-11-27 at 11 41 42](https://github.com/yoctoproject/vscode-bitbake/assets/32394/c9f0629d-bc43-415b-a627-8125bd9828b4)

Removing the `"` inside `s` will highlight correctly, so the single quote is being treated as the end of the quoted string:

![Screenshot 2023-11-27 at 11 42 24](https://github.com/yoctoproject/vscode-bitbake/assets/32394/8d4cea1e-5e7f-4ec4-b1fd-86ff65988b93)

**Comment by rossburton** [comment]
Should the additional extensions be working for me? (This is a snapshot from a week or so ago)

**Comment by WilsonZiweiWang** [comment]
Just confirmed with my colleague @idillon-sfl  who has been working on the embedded feature. Right now it can't handle the highlighting the way it handles the completion and the hover since VSCode doesn't provide an API to do so. That being said, the highlighting right now is coming solely from the bitbake extension (which uses regex in `bitbake.tmLanguage.json`). We are researching other alternatives to handle python and shell highlighting with something more reliable.
