### ISSUE TITLE
Add a window to browse generated image rootfs

### ISSUE THREAD

**Issue by Paullgk** [yoctoproject/vscode-bitbake#66]
Regularly, I need to browse the generated image rootfs to check if my recipe modification are well applied on my package. A very nice feature would be a window in Bitbake extension with the ability to browse the generated rootfs directory.

**Comment by deribaucourt** [comment]
That's also an idea I had! Although I suggest a more generic approach for any recipe. Suggestions to implement this:
 1. Add a contextual menu command to open a recipe's TMPDIR (depends on the bitbake -e feature we currently are developing)
 2. Add this dir to the recipes view

**Comment by deribaucourt** [comment]
We now have the ability to expand variable values!
they are in the server though.
Here are the available vars we could use for browsing:
 - WORKDIR
 - S
 - B
 - DEVSHELL_STARTDIR (usually S, but customizable)
I think Workdir is best because it also contains the logs, the sources, the package splits. It's the most complete one. Of course users need to know what all of it is. It's not just the sources or the build. But I think users going into TMPDIR have to know what they are doing. devtool provides a more usual experience where just the sources are openend. Havin logs, builds, splits allows to fully debug the build that's hapenning.
